[package]
name = "nft-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nft_daemon"
path = "src/lib.rs"


[dependencies]
tokio = {version = "1.21.2", features = ["full"]}
axum = "0.5.17"
sqlx = { version = "0.6.2", features = [ "runtime-tokio-rustls", "sqlite" , "migrate", "chrono"] }
serde = { version = "1.0.147", features = ["derive"] }
tracing-subscriber = "0.3.16"
tracing = "0.1"
anyhow = "1.0.66"
dotenv = "0.15.0"
rand = "0.8.5"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio"]}
