[env]
DB_PATH = "./tmp/dev.db"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]


[tasks.db-clean]
command = "rm"
args = ['${DB_PATH}']

[tasks.remigrate]
dependencies = [
    'db-clean',
    'db-create',
    'migrate'
]

[tasks.migrate]
script = ['''
#!/usr/bin/env bash
sqlx migrate run --database-url sqlite:${DB_PATH}
''']

[tasks.db-create]
script = ['''
#!/usr/bin/env bash
sqlx database create --database-url sqlite:${DB_PATH}
''']

